-type username()        :: string().
-type client_id()       :: string().
-type topic()           :: string().
-type qos()             :: 0 | 1 | 2.
-type routing_key()     :: string().
-type payload()         :: binary().
-type msg_ref()         :: binary().
-type msg_id()          :: undefined | 1..65535.
-type flag()            :: true | false.
-type connack_rc()      :: 0 | 1 | 2 | 3 | 4 | 5.
-type proto_version()   :: 3 | 4 | 131.
-type frame_type()      :: byte().
-type plugin_id()       :: {plugin, atom(), pid()}.

